"""create knowledge documents

Revision ID: e4f8c3970078
Revises: a377b2f6df11
Create Date: 2026-10-03 19:51:56.201535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f8c3970078'
down_revision: Union[str, Sequence[str], None] = 'a377b2f6df11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_key', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        "uq_knowledge_documents_active_policy_key",
        "knowledge_documents",
        ["policy_key"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_knowledge_documents_active_policy_key",
        table_name="knowledge_documents",
    )
    op.drop_table("knowledge_documents")
    # ### end Alembic commands ###
